{{- if .Values.app.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "higgs-domino.fullname" . }}
  labels:
    {{- include "higgs-domino.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "higgs-domino.fullname" . }}
  minReplicas: {{ .Values.app.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.app.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.app.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.app.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.app.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.app.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- with .Values.app.autoscaling.customMetrics }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.app.autoscaling.behavior }}
  behavior:
    {{- with .Values.app.autoscaling.behavior.scaleDown }}
    scaleDown:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.app.autoscaling.behavior.scaleUp }}
    scaleUp:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}