{{- if .Values.app.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "higgs-domino.fullname" . }}
  labels:
    {{- include "higgs-domino.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "higgs-domino.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.app.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.app.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  {{- if .Values.app.networkPolicy.ingress.enabled }}
  ingress:
    # Allow ingress from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.app.networkPolicy.ingress.ingressNamespace | default "ingress-nginx" }}
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 3001
    # Allow ingress from same namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 3001
    # Allow monitoring from Prometheus
    {{- if .Values.prometheus.enabled }}
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 3000
    {{- end }}
    # Custom ingress rules
    {{- with .Values.app.networkPolicy.ingress.rules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if .Values.app.networkPolicy.egress.enabled }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow HTTPS to external services
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Allow HTTP to external services
    - to: []
      ports:
        - protocol: TCP
          port: 80
    # Allow connection to PostgreSQL
    {{- if .Values.postgresql.enabled }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
      ports:
        - protocol: TCP
          port: 5432
    {{- else }}
    # Allow connection to external PostgreSQL
    - to: []
      ports:
        - protocol: TCP
          port: {{ .Values.externalDatabase.port | default 5432 }}
    {{- end }}
    # Allow connection to Redis
    {{- if .Values.redis.enabled }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
      ports:
        - protocol: TCP
          port: 6379
    {{- else }}
    # Allow connection to external Redis
    - to: []
      ports:
        - protocol: TCP
          port: {{ .Values.externalRedis.port | default 6379 }}
    {{- end }}
    # Allow SMTP for email
    - to: []
      ports:
        - protocol: TCP
          port: 587
        - protocol: TCP
          port: 465
        - protocol: TCP
          port: 25
    # Allow connection to payment gateways
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Custom egress rules
    {{- with .Values.app.networkPolicy.egress.rules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
---
{{- if and .Values.postgresql.enabled .Values.app.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "higgs-domino.fullname" . }}-postgresql
  labels:
    {{- include "higgs-domino.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    # Allow connection from main app
    - from:
        - podSelector:
            matchLabels:
              {{- include "higgs-domino.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5432
    # Allow connection from backup jobs
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: backup
      ports:
        - protocol: TCP
          port: 5432
---
{{- end }}
{{- if and .Values.redis.enabled .Values.app.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "higgs-domino.fullname" . }}-redis
  labels:
    {{- include "higgs-domino.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    # Allow connection from main app
    - from:
        - podSelector:
            matchLabels:
              {{- include "higgs-domino.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 6379
{{- end }}
{{- end }}