apiVersion: v1
kind: Secret
metadata:
  name: {{ include "higgs-domino.secretName" . }}
  labels:
    {{- include "higgs-domino.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials
  db-password: {{ .Values.app.secrets.dbPassword | default (include "higgs-domino.postgresql.password" .) | b64enc | quote }}
  
  # Redis credentials
  {{- if .Values.redis.auth.enabled }}
  redis-password: {{ .Values.app.secrets.redisPassword | default .Values.redis.auth.password | b64enc | quote }}
  {{- end }}
  
  # JWT secret
  jwt-secret: {{ .Values.app.secrets.jwtSecret | default (randAlphaNum 64) | b64enc | quote }}
  
  # Payment API keys
  stripe-secret-key: {{ .Values.app.secrets.stripeSecretKey | default "sk_test_" | b64enc | quote }}
  stripe-webhook-secret: {{ .Values.app.secrets.stripeWebhookSecret | default "whsec_" | b64enc | quote }}
  paypal-client-secret: {{ .Values.app.secrets.paypalClientSecret | default "paypal_secret" | b64enc | quote }}
  
  # Email credentials
  email-password: {{ .Values.app.secrets.emailPassword | default "email_password" | b64enc | quote }}
  
  # Firebase credentials
  firebase-private-key: {{ .Values.app.secrets.firebasePrivateKey | default "firebase_key" | b64enc | quote }}
  firebase-client-email: {{ .Values.app.secrets.firebaseClientEmail | default "firebase@project.iam.gserviceaccount.com" | b64enc | quote }}
  firebase-project-id: {{ .Values.app.secrets.firebaseProjectId | default "higgs-domino" | b64enc | quote }}
  
  # External API keys
  google-maps-api-key: {{ .Values.app.secrets.googleMapsApiKey | default "google_maps_key" | b64enc | quote }}
  facebook-app-secret: {{ .Values.app.secrets.facebookAppSecret | default "facebook_secret" | b64enc | quote }}
  twitter-api-secret: {{ .Values.app.secrets.twitterApiSecret | default "twitter_secret" | b64enc | quote }}
  
  # Encryption keys
  encryption-key: {{ .Values.app.secrets.encryptionKey | default (randAlphaNum 32) | b64enc | quote }}
  session-secret: {{ .Values.app.secrets.sessionSecret | default (randAlphaNum 64) | b64enc | quote }}
  
  # Webhook secrets
  webhook-secret: {{ .Values.app.secrets.webhookSecret | default (randAlphaNum 32) | b64enc | quote }}
  
  # Admin credentials
  admin-password: {{ .Values.app.secrets.adminPassword | default "admin123" | b64enc | quote }}
  
  # Monitoring credentials
  prometheus-password: {{ .Values.app.secrets.prometheusPassword | default "prometheus123" | b64enc | quote }}
  grafana-admin-password: {{ .Values.app.secrets.grafanaAdminPassword | default .Values.grafana.adminPassword | b64enc | quote }}
  
  # SSL/TLS certificates (if needed)
  {{- if .Values.app.secrets.tlsCert }}
  tls-cert: {{ .Values.app.secrets.tlsCert | b64enc | quote }}
  {{- end }}
  {{- if .Values.app.secrets.tlsKey }}
  tls-key: {{ .Values.app.secrets.tlsKey | b64enc | quote }}
  {{- end }}
  
  # OAuth secrets
  oauth-client-secret: {{ .Values.app.secrets.oauthClientSecret | default "oauth_secret" | b64enc | quote }}
  
  # SMS/Push notification secrets
  twilio-auth-token: {{ .Values.app.secrets.twilioAuthToken | default "twilio_token" | b64enc | quote }}
  fcm-server-key: {{ .Values.app.secrets.fcmServerKey | default "fcm_key" | b64enc | quote }}
  
  # Analytics secrets
  analytics-api-key: {{ .Values.app.secrets.analyticsApiKey | default "analytics_key" | b64enc | quote }}
  
  # Backup encryption key
  backup-encryption-key: {{ .Values.app.secrets.backupEncryptionKey | default (randAlphaNum 32) | b64enc | quote }}