apiVersion: v1
kind: Service
metadata:
  name: {{ include "higgs-domino.fullname" . }}
  labels:
    {{- include "higgs-domino.labels" . | nindent 4 }}
  {{- with .Values.app.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.app.service.ports.websocket }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "higgs-domino.selectorLabels" . | nindent 4 }}